- name: PostgreSQL install
  hosts: sfu_vm
  become: yes

  vars_files:
    - db_vars.yml
    - postgres_vars.yml

  pre_tasks:
    - name:
      dnf:
        name:
          - python3-pip
          - "@postgresql:15/client"
          - "@postgresql:15/server"
        state: present

  tasks:
    - name: Find out if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{pg_data}}/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL with checksums
      become: yes
      become_user: postgres 
      shell: "initdb -D {{pg_data}} -k --no-instructions"
      when: not postgres_data.stat.exists
 
    - name: Start and enable services
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
