- name: PostgreSQL install
  hosts: sfu_vm
  become: yes

  vars_files:
    - db_vars.yml

  pre_tasks:
    - name: Install packages
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql15
        - postgresql15-server

    - name: Install Python packages
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

  tasks:
    - name: Find out if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{pg_data}}/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL with checksums 
      shell: "initdb -D {{pg_data}} -k -U postgres --no-instructions`"
      when: not postgres_data.stat.exists
 
    - name: Start and enable services
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
